// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojyhxpyiborimrpytntt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeWh4cHlpYm9yaW1ycHl0bnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3MjY2NDQsImV4cCI6MjEwNDMwMjY0NH0.gP1aS_7v62Dk-JtBBOJU9Ic8UmWEhir3-LPOAlbcjBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});