import type { BannerTemplate } from "@/types/banner";

export const BANNER_TEMPLATES: BannerTemplate[] = [
  {
    id: "flash-sale-fire",
    name: "Oferta Relâmpago (Chamas)",
    category: "promocional",
    description:
      "Design de alta urgência com gradiente vermelho e laranja ardente, ideal para promoções com tempo limitado.",
    defaultConfig: {
      templateId: "flash-sale-fire",
      title: "SMARTPHONE GALAXY S24 ULTRA 512GB",
      subtitle: "Menor preço dos últimos 60 dias!",
      originalPrice: "R$ 6.999,00",
      currentPrice: "R$ 4.199,00",
      discountBadge: "40% OFF",
      installmentText: "em até 10x sem juros",
      couponCode: "RELAMPAGO40",
      buttonText: "PEGAR OFERTA AGORA",
      imageUrl:
        "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "mercado-livre",
      tagline: "⚡ OFERTA POR TEMPO LIMITADO",
      showSticker: true,
      stickerText: "ÚLTIMAS UNIDADES",
      style: {
        backgroundGradient: "from-red-600 via-rose-600 to-orange-500",
        textColor: "text-white",
        accentColor: "text-yellow-300",
        badgeBg: "bg-yellow-400",
        badgeText: "text-red-950 font-extrabold",
        buttonBg: "bg-yellow-400 hover:bg-yellow-300 text-red-950 font-black",
        buttonText: "COMPRAR COM DESCONTO",
        patternOverlay: "dots",
        glassmorphism: true,
      },
    },
  },
  {
    id: "black-friday-gold",
    name: "Black Friday Deluxe",
    category: "datas_especiais",
    description:
      "Visual premium escuro com detalhes em dourado e alto contraste para campanhas de Black Friday.",
    defaultConfig: {
      templateId: "black-friday-gold",
      title: "HEADSET GAMER WIRELESS 7.1 SURROUND",
      subtitle: "Áudio imersivo de alta fidelidade com cancelamento de ruído",
      originalPrice: "R$ 899,00",
      currentPrice: "R$ 349,90",
      discountBadge: "61% OFF",
      installmentText: "12x de R$ 29,15",
      couponCode: "BLACKFRIDAY",
      buttonText: "GARANTIR COM O DESCONTO",
      imageUrl:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "amazon",
      tagline: "🖤 BLACK FRIDAY EXCLUSIVA",
      showSticker: true,
      stickerText: "MENOR PREÇO DO ANO",
      style: {
        backgroundGradient: "from-slate-950 via-zinc-900 to-black",
        textColor: "text-white",
        accentColor: "text-amber-400",
        badgeBg: "bg-gradient-to-r from-amber-400 to-yellow-500",
        badgeText: "text-black font-black",
        buttonBg: "bg-gradient-to-r from-amber-400 to-yellow-500 text-black font-extrabold",
        buttonText: "COMPRAR AGORA",
        patternOverlay: "grid",
        glassmorphism: true,
      },
    },
  },
  {
    id: "cashback-emerald",
    name: "Cashback & Economia",
    category: "exclusivo",
    description:
      "Estilo moderno em tom esmeralda focado em benefícios de dinheiro de volta e cupons.",
    defaultConfig: {
      templateId: "cashback-emerald",
      title: 'SMART TV 55" 4K UHD OLED',
      subtitle: "Receba até 15% de volta comprando pelo link de afiliado",
      originalPrice: "R$ 3.899,00",
      currentPrice: "R$ 2.499,00",
      discountBadge: "R$ 1.400 OFF",
      installmentText: "Frete Grátis para todo o Brasil",
      couponCode: "CASHBACKVIP",
      buttonText: "RESGATAR CASHBACK",
      imageUrl:
        "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "magalu",
      tagline: "💰 CASHBACK GARANTIDO",
      showSticker: true,
      stickerText: "15% DE VOLTA",
      style: {
        backgroundGradient: "from-emerald-900 via-teal-800 to-cyan-900",
        textColor: "text-white",
        accentColor: "text-emerald-300",
        badgeBg: "bg-emerald-400",
        badgeText: "text-emerald-950 font-black",
        buttonBg: "bg-emerald-400 hover:bg-emerald-300 text-emerald-950 font-extrabold",
        buttonText: "PEGAR CUPOM + CASHBACK",
        patternOverlay: "waves",
        glassmorphism: true,
      },
    },
  },
  {
    id: "frete-gratis-cyan",
    name: "Frete Grátis & Entrega Rápida",
    category: "promocional",
    description:
      "Azul vibrante e limpo, excelente para destacar entregas sem custo e enviadas hoje.",
    defaultConfig: {
      templateId: "frete-gratis-cyan",
      title: "AIR FRYER DIGITAL 4L INOX",
      subtitle: "Cozinhe sem óleo com rápida circulação de ar quente",
      originalPrice: "R$ 499,00",
      currentPrice: "R$ 249,00",
      discountBadge: "50% OFF",
      installmentText: "Entrega expressa grátis no mesmo dia",
      couponCode: "FRETEFREE",
      buttonText: "APROVEITAR FRETE GRÁTIS",
      imageUrl:
        "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "shopee",
      tagline: "🚚 FRETE 100% GRÁTIS",
      showSticker: true,
      stickerText: "CHEGA HOJE",
      style: {
        backgroundGradient: "from-blue-700 via-indigo-600 to-cyan-500",
        textColor: "text-white",
        accentColor: "text-cyan-200",
        badgeBg: "bg-cyan-300",
        badgeText: "text-blue-950 font-extrabold",
        buttonBg: "bg-white hover:bg-cyan-50 text-blue-900 font-bold",
        buttonText: "VER NO SITE",
        patternOverlay: "dots",
        glassmorphism: true,
      },
    },
  },
  {
    id: "cyber-neon-violet",
    name: "Cyber Neon Glow",
    category: "exclusivo",
    description: "Estilo futurista cyberpunk roxo e neon, excelente para tech, celulares e games.",
    defaultConfig: {
      templateId: "cyber-neon-violet",
      title: "CONSOLE PLAYSTATION 5 SLIM 1TB",
      subtitle: "Bundle exclusivo com 2 jogos inclusos",
      originalPrice: "R$ 4.499,00",
      currentPrice: "R$ 3.399,00",
      discountBadge: "SÓ HOJE",
      installmentText: "em até 10x sem juros",
      couponCode: "PLAYNEON",
      buttonText: "COMPRAR NO MERCADO LIVRE",
      imageUrl:
        "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "mercado-livre",
      tagline: "🎮 TECH & GAMES SALE",
      showSticker: true,
      stickerText: "IMPERDÍVEL",
      style: {
        backgroundGradient: "from-purple-950 via-indigo-900 to-fuchsia-900",
        textColor: "text-white",
        accentColor: "text-fuchsia-300",
        badgeBg: "bg-fuchsia-500",
        badgeText: "text-white font-extrabold",
        buttonBg: "bg-gradient-to-r from-fuchsia-500 to-purple-500 text-white font-extrabold",
        buttonText: "GARANTIR MEU CONSOLE",
        patternOverlay: "grid",
        glassmorphism: true,
      },
    },
  },
  {
    id: "clean-nordic-white",
    name: "Minimalista Clean E-Commerce",
    category: "minimalista",
    description:
      "Estilo limpo, elegante e minimalista estilo Apple para marcas de luxo e estética premium.",
    defaultConfig: {
      templateId: "clean-nordic-white",
      title: "SMARTWATCH SERIE 9 ALUMINUM 45MM",
      subtitle: "Monitoramento de saúde com sensor de frequência e oxigênio",
      originalPrice: "R$ 3.299,00",
      currentPrice: "R$ 1.999,00",
      discountBadge: "39% OFF",
      installmentText: "com envio grátis e nota fiscal",
      couponCode: "SMART10",
      buttonText: "CONFIRMAR OFERTA",
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "amazon",
      tagline: "✨ EDICÃO LIMITADA",
      showSticker: false,
      stickerText: "DESTAQUE",
      style: {
        backgroundGradient: "from-slate-100 via-gray-100 to-slate-200",
        textColor: "text-slate-900",
        accentColor: "text-slate-600",
        badgeBg: "bg-slate-900",
        badgeText: "text-white font-bold",
        buttonBg: "bg-slate-900 hover:bg-slate-800 text-white font-bold",
        buttonText: "COMPRAR AGORA",
        patternOverlay: "none",
        glassmorphism: false,
      },
    },
  },
  {
    id: "story-reels-vertical",
    name: "Story & Status (Vertical 9:16)",
    category: "social",
    description:
      "Formato vertical 9:16 perfeito para publicar em Stories do Instagram, WhatsApp Status e TikTok.",
    defaultConfig: {
      templateId: "story-reels-vertical",
      title: "NOTEBOOK GAMER RTX 4060 16GB",
      subtitle: "Processador Intel i7 13ª Geração | SSD 1TB NVMe",
      originalPrice: "R$ 7.499,00",
      currentPrice: "R$ 4.999,00",
      discountBadge: "R$ 2.500 OFF",
      installmentText: "10x sem juros no cartão",
      couponCode: "STORYSECRET",
      buttonText: "ARRASTE OU CLIQUE AQUI",
      imageUrl:
        "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "9:16",
      marketplace: "aliexpress",
      tagline: "🔥 ACHADO DO DIA",
      showSticker: true,
      stickerText: "LINK NA BIO",
      style: {
        backgroundGradient: "from-rose-950 via-purple-900 to-violet-950",
        textColor: "text-white",
        accentColor: "text-rose-300",
        badgeBg: "bg-rose-500",
        badgeText: "text-white font-black",
        buttonBg: "bg-gradient-to-r from-rose-500 to-amber-500 text-white font-extrabold",
        buttonText: "VER OFERTA NO STORIES",
        patternOverlay: "dots",
        glassmorphism: true,
      },
    },
  },
  {
    id: "web-banner-horizontal",
    name: "Banner Web Landscape (16:9)",
    category: "social",
    description:
      "Banner panorâmico ideal para anúncios em sites, blogs, topo de e-mail marketing e anúncios.",
    defaultConfig: {
      templateId: "web-banner-horizontal",
      title: "FONE DE OUVIDO BLUETOOTH TWS",
      subtitle: "Autonomia de bateria de 30 horas com estojo recarregável",
      originalPrice: "R$ 299,00",
      currentPrice: "R$ 89,90",
      discountBadge: "70% OFF",
      installmentText: "Frete Grátis para todo Brasil",
      couponCode: "AUDIO70",
      buttonText: "GARANTIR DESCONTO EXCLUSIVO",
      imageUrl:
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
      imageScale: 1,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "16:9",
      marketplace: "shopee",
      tagline: "🎧 SUPER DESCONTO AUDIO",
      showSticker: true,
      stickerText: "OFERTA DO DIA",
      style: {
        backgroundGradient: "from-orange-600 via-amber-500 to-yellow-400",
        textColor: "text-slate-950",
        accentColor: "text-orange-950",
        badgeBg: "bg-slate-950",
        badgeText: "text-amber-400 font-black",
        buttonBg: "bg-slate-950 hover:bg-slate-900 text-white font-extrabold",
        buttonText: "APROVEITAR NO SITE",
        patternOverlay: "waves",
        glassmorphism: true,
      },
    },
  },
  {
    id: "post-grupo-clean",
    name: "Post de Grupo Minimalista (Sem Texto)",
    category: "social",
    description:
      "Padrão Minimalista Clean E-Commerce para grupos de Telegram/WhatsApp: sem nome e texto do produto, imagem do produto em destaque maior, preços, cupom e fundo elegante.",
    defaultConfig: {
      templateId: "post-grupo-clean",
      title: "SMARTWATCH SERIE 9 ALUMINUM 45MM",
      subtitle: "Monitoramento de saúde com sensor de frequência e oxigênio",
      originalPrice: "R$ 3.299,00",
      currentPrice: "R$ 1.999,00",
      discountBadge: "39% OFF",
      installmentText: "com envio grátis e nota fiscal",
      couponCode: "SMART10",
      buttonText: "COMPRAR AGORA",
      showButton: false,
      showTitle: false,
      showSubtitle: false,
      showPrices: true,
      showBadge: true,
      showCoupon: true,
      showTagline: true,
      showMarketplace: true,
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
      imageScale: 1.15,
      imagePositionX: 0,
      imagePositionY: 0,
      aspectRatio: "1:1",
      marketplace: "amazon",
      tagline: "📢 POST DE GRUPO",
      showSticker: false,
      stickerText: "",
      style: {
        backgroundGradient: "from-slate-100 via-gray-100 to-slate-200",
        textColor: "text-slate-900",
        accentColor: "text-slate-600",
        badgeBg: "bg-slate-900",
        badgeText: "text-white font-bold",
        buttonBg: "bg-slate-900 hover:bg-slate-800 text-white font-bold",
        buttonText: "COMPRAR AGORA",
        patternOverlay: "none",
        glassmorphism: false,
      },
    },
  },
];
